name: generate coverage and upload to Codecov
on:
  push:
    branches:
      - "main"
      - "dev"
      - "docs"
  pull_request:
    branches:
      - "main"
      - "dev"
      - "docs"

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-dev.txt
        python --version
        which python

    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        python ./scripts/convert_notebook_tests.py
        pytest -v --cov=holodeck --cov-report=xml --color=yes

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        # directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        # files: ./coverage1.xml,./coverage2.xml
        # path_to_write_report: ./coverage/codecov_report.txt
        verbose: true